export enum EPage {
  WELCOME = "welcomePage",
  SIGN_IN = "signInPage",
  SIGN_UP = "signUpPage",
  ADD_PET = "addPetPage",
  PET = "petPage",
  CURRENT_REMINDERS = "currentRemindersPage",
  REMINDERS_LIST = "remindersListPage",
  CREATE_REMINDER = "createReminderPage",
  MAIN = "mainPage",
  HOME = "homePage",
  MY_PETS = "myPetsPage",
  LIBRARY = "libraryPage",
  PROFILE = "profilePAge",
  SUCCESS_PAGE = "successPage",
}
