export enum EPage {
  WELCOME = "welcomePage",
  SIGNIN = "signInPage",
  SIGNUP = "signUpPage",
  ADDPET = "addPetPage",
  PET = "petPage",
  CURRENTREMINDERS = "currentRemindersPage",
  REMINDERSLIST = "remindersListPage",
  CREATEREMINDER = "createReminderPage",
  EDIT = "editPage",
  MAIN = "mainPage",
  HOME = "homePage",
  MYPETS = "myPetsPage",
  LIBRARY = "libraryPage",
  PROFILE = "profilePAge",
}
