export enum EPage {
  WELCOME = "welcomePage",
  SIGN_IN = "signInPage",
  SIGN_UP = "signUpPage",
  ADD_PET = "addPetPage",
  PET = "petPage",
  CURRENT_REMINDERS = "currentRemindersPage",
  REMINDERS_LIST = "remindersListPage",
  CREATE_REMINDER = "createReminderPage",
  MAIN = "mainPage",
  HOME = "homePage",
  MY_PETS = "myPetsPage",
  LIBRARY = "libraryPage",
  PROFILE = "profilePage",
  SUCCESS_PAGE = "successPage",
  CHANGE_PROFILE_PAGE = "changeProfilePage",
  APPOINTMENT_LIST = "appointmentListPage",
  CREATE_APPOINTMENT = "createAppointmentPage",
  ABUSE_INFORMATION = "abuseInformationPage",
  MAP = "map_page",
  PET_STATUS = "petStatusPage",
  UPDATE_PAGE = "updatePage",
}
